on:
  push:
    branches:
      - release-workflow
  #  branches:
  #    - master

name: Release

jobs:
  release:
    name: release ${{ matrix.package }} ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - target: x86_64-pc-windows-gnu
            # archive: zip
          #   package: [pcmg rack-designer]
          - target: x86_64-unknown-linux-musl
            # archive: tar.gz tar.xz tar.zst
            package: [pcmg rack-designer]
          # - target: x86_64-apple-darwin
            # archive: zip
          #   package: [pcmg rack-designer]
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: sudo apt-get install -y libasound2 libasound2-dev libatk1.0-0 libgtk-3-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --package ${{ matrix.package }}
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/${{ matrix.package }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
