on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            extension: ''
          - target: x86_64-pc-windows-gnu
            extension: '.exe'
          - target: x86_64-apple-darwin
            extension: '.app'
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: sudo apt-get install -y libasound2 libasound2-dev libatk1.0-0 libgtk-3-dev libglib2.0-dev gcc-mingw-w64 zip

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --target ${{ matrix.target }} --release --package pcmg --package rack-designer
      - name: Prepare artifacts
        run: |
          mkdir artifacts &&
          mv target/${{ matrix.target }}/release/pcmg${{ matrix.extension }} artifacts/pcmg-${{ matrix.target }}${{ matrix.extension }} &&
          mv target/${{ matrix.target }}/release/rack-designer${{ matrix.extension }} artifacts/rack-designer-${{ matrix.target }}${{ matrix.extension }}
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/pcmg-${{ matrix.target }}${{ matrix.extension }}
            artifacts/rack-designer-${{ matrix.target }}${{ matrix.extension }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
