on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl:
            extension: ''
          - x86_64-pc-windows-gnu:
            extension: '.exe'
          - x86_64-apple-darwin:
            extension: '.app'
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: sudo apt-get install -y libasound2 libasound2-dev libatk1.0-0 libgtk-3-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --package pcmg --package rack-designer
      - name: Prepare artifacts
        run: |
          mkdir artifacts &&
          mv target/release/pcmg${{ matrix.target.extension }} artifacts/pcmg-${{ matrix.target }}${{ matrix.target.extension }} &&
          mv target/release/rack-designer${{ matrix.target.extension }} artifacts/rack-designer-${{ matrix.target }}${{ matrix.target.extension }}
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/pcmg-${{ matrix.target }}${{ matrix.target.extension }}
            artifacts/rack-designer-${{ matrix.target }}${{ matrix.target.extension }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
