on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    name: ${{ matrix.package }} ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
            # - x86_64-pc-windows-gnu
            # - x86_64-apple-darwin
        package:
          - pcmg
          - rack-designer
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: sudo apt-get install -y libasound2 libasound2-dev libatk1.0-0 libgtk-3-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --package ${{ matrix.package }}
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/${{ matrix.package }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
